/**
 * Configuration builders for the scenarios.
 *
 * The plugin's own surface is (a) the composition row's `config.servers` list
 * in the profile patch and (b) the persisted `mcp-support` settings section in
 * `$DSH_HOME/settings.yaml`. Both accept exactly the native
 * `@deepseek-ai/dsh-mcp-client` union, so these helpers emit that union and
 * nothing else.
 *
 * Documents are written as JSON: YAML 1.2 is a JSON superset and dsh parses
 * both files with a YAML loader, so the suite needs no YAML dependency.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fixturesDir } from './paths'

export const SETTINGS_NAMESPACE = 'mcp-support'
export const STATUS_ENDPOINT = '/plugins/@royenheart/dsh-plugin-mcp-support/status'

/** The MCP stdio fixture server shipped with this suite. */
export function stdioFixtureScript(): string {
  return path.join(fixturesDir(), 'mcp-stdio-server.mjs')
}

/** The MCP streamable-http fixture server shipped with this suite. */
export function httpFixtureScript(): string {
  return path.join(fixturesDir(), 'mcp-http-server.mjs')
}

export interface StdioFixtureOptions {
  /** File the fixture appends `ready` / `method <name>` lines to. */
  markerFile?: string
  command?: string
  args?: string[]
  cwd?: string
  env?: Record<string, string>
  failOnStartupError?: boolean
  toolCallTimeoutMs?: number
  maxInstructionBytes?: number
  reconnect?: Record<string, unknown>
}

/** A stdio server config that runs a fixture through `node`. */
export function stdioFixture(serverName: string, options: StdioFixtureOptions = {}): Record<string, unknown> {
  const config: Record<string, unknown> = {
    transport: 'stdio',
    serverName,
    command: options.command ?? process.execPath,
    args: options.args ?? [stdioFixtureScript()],
    cwd: options.cwd ?? fixturesDir(),
    env: { ...(options.env ?? {}) },
    failOnStartupError: options.failOnStartupError ?? false,
  }
  if (options.markerFile !== undefined) {
    ;(config.env as Record<string, string>).MCP_E2E_READY_FILE = options.markerFile
  }
  if (options.toolCallTimeoutMs !== undefined) config.toolCallTimeoutMs = options.toolCallTimeoutMs
  if (options.maxInstructionBytes !== undefined) config.maxInstructionBytes = options.maxInstructionBytes
  if (options.reconnect !== undefined) config.reconnect = options.reconnect
  return config
}

/** A stdio server config whose command cannot start (mount-failure scenarios). */
export function deadStdioFixture(serverName: string, options: { failOnStartupError?: boolean } = {}): Record<string, unknown> {
  return {
    transport: 'stdio',
    serverName,
    command: path.join(fixturesDir(), 'definitely-not-an-executable'),
    args: [],
    env: {},
    cwd: fixturesDir(),
    failOnStartupError: options.failOnStartupError ?? true,
    toolCallTimeoutMs: 5_000,
    reconnect: { enabled: false },
  }
}

export interface HttpFixtureOptions {
  url: string
  headers?: Record<string, string>
  failOnStartupError?: boolean
  toolCallTimeoutMs?: number
  reconnect?: Record<string, unknown>
}

/** A streamable-http server config pointing at the HTTP fixture. */
export function httpFixture(serverName: string, options: HttpFixtureOptions): Record<string, unknown> {
  return {
    transport: 'streamable-http',
    serverName,
    url: options.url,
    headers: { ...(options.headers ?? {}) },
    failOnStartupError: options.failOnStartupError ?? false,
    toolCallTimeoutMs: options.toolCallTimeoutMs ?? 15_000,
    ...(options.reconnect === undefined ? {} : { reconnect: options.reconnect }),
  }
}

/** The profile patch row that overrides the bundle-inserted `mcp-support` entry. */
export function compositionPatch(servers: unknown[] | null): unknown[] {
  const row: Record<string, unknown> = { id: SETTINGS_NAMESPACE }
  if (servers !== null) row.config = { servers }
  return [row]
}

/** The persisted `$DSH_HOME/settings.yaml` document for a server list. */
export function settingsDocument(servers: unknown[]): Record<string, unknown> {
  return { [SETTINGS_NAMESPACE]: { servers } }
}

/** Write a YAML file whose content is JSON (valid YAML 1.2). */
export function writeYamlDocument(file: string, value: unknown, note = 'generated by the e2e harness'): void {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, `# ${note}\n${JSON.stringify(value, null, 2)}\n`, 'utf8')
}
